### ISSUE TITLE
Can not set client order id for orders while create batch orders.

### ISSUE THREAD

**Issue by serj20** [JKorf/BitMart.Net#6]
**Describe the bug**
Can not set 'client order id' for orders while create batch orders.

**To Reproduce**
Create batch orders with custom 'order client id'.

**Expected behavior**
Orders was created, and have corresponding 'order client id'.

**Note**
BitMart.NET sends the property name "client_order_id" instead of "clientOrderId" which is expected for function https://developer-pro.bitmart.com/en/spot/#new-batch-order-v4-signed.

**Comment by JKorf** [comment]
Fixed in latest version
